version: '3'
services:
  db-product:
    container_name: db-store
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms-store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432